> python -m runame: Django CI
> python -m runx.runx  scripts/train_cityscapes_sota.yml -irunx.runx> python -m runx.runx scripts/dump_folder.yml -i> python -m runx.runx scripts/train_cityscapes.yml -i> python -m runx.runx scripts/eval_mapillary.yml -i> python -m runx.runx scripts/dump_cityscapes.yml -i
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
